name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Trigger my downstream workflow
      run: |
        curl -XPOST -u ${{ secrets.PAT_TOKEN }} -H "Accept:application/vnd.github" -H "Content-Type:application/json" https://api.github.com/repos/Olawale/bbhs-97-api/blob/master/.github/workflows/docker-image.yml/dispatches --data '{"ref": "master" }'
